/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatePicker: typeof import('./components/datePicker.vue')['default']
    PlataformLayout: typeof import('./components/layouts/PlataformLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/sideMenu.vue')['default']
  }
}
