/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/plataform/': RouteRecordInfo<'/plataform/', '/plataform', Record<never, never>, Record<never, never>>,
    '/plataform/auth/forgotPassword': RouteRecordInfo<'/plataform/auth/forgotPassword', '/plataform/auth/forgotPassword', Record<never, never>, Record<never, never>>,
    '/plataform/auth/login': RouteRecordInfo<'/plataform/auth/login', '/plataform/auth/login', Record<never, never>, Record<never, never>>,
    '/plataform/auth/register': RouteRecordInfo<'/plataform/auth/register', '/plataform/auth/register', Record<never, never>, Record<never, never>>,
    '/plataform/locations/[id]': RouteRecordInfo<'/plataform/locations/[id]', '/plataform/locations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/plataform/locations/add': RouteRecordInfo<'/plataform/locations/add', '/plataform/locations/add', Record<never, never>, Record<never, never>>,
    '/plataform/manager/': RouteRecordInfo<'/plataform/manager/', '/plataform/manager', Record<never, never>, Record<never, never>>,
    '/plataform/manager/clients/': RouteRecordInfo<'/plataform/manager/clients/', '/plataform/manager/clients', Record<never, never>, Record<never, never>>,
    '/plataform/manager/clients/[id]': RouteRecordInfo<'/plataform/manager/clients/[id]', '/plataform/manager/clients/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/plataform/manager/decorations': RouteRecordInfo<'/plataform/manager/decorations', '/plataform/manager/decorations', Record<never, never>, Record<never, never>>,
    '/plataform/manager/hall': RouteRecordInfo<'/plataform/manager/hall', '/plataform/manager/hall', Record<never, never>, Record<never, never>>,
    '/plataform/manager/locations': RouteRecordInfo<'/plataform/manager/locations', '/plataform/manager/locations', Record<never, never>, Record<never, never>>,
  }
}
